# Generated by Django 4.0.4 on 2022-09-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_remove_song_title_song_author_song_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.CharField(default='album name', max_length=40),
        ),
        migrations.AlterField(
            model_name='song',
            name='author',
            field=models.CharField(default='Author name', max_length=40),
        ),
        migrations.AlterField(
            model_name='song',
            name='name',
            field=models.CharField(default='Song name', max_length=40),
        ),
    ]
