# Generated by Django 4.0.4 on 2022-09-19 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='page_url',
            field=models.CharField(blank=True, default='Albums page url', max_length=140),
        ),
        migrations.AddField(
            model_name='song',
            name='albumname',
            field=models.CharField(default='album name', max_length=40),
        ),
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(db_index=True, default='album name', max_length=40),
        ),
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.album'),
        ),
    ]
